version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src    # Mount local src directory into the container
      - /usr/src/app/node_modules # Ensure node_modules persists inside the container
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001" # RedisInsight UI will be accessible at http://localhost:8001
    depends_on:
      - redis
