version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Add other environment variables as needed
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      target: development
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - app-network

  pocket:
    image: ghcr.io/pokt-network/pocket-v0:latest
    container_name: pocket
    ports:
      - "8081:8081"   # Pocket RPC port
      - "8082:8082"   # Pocket consensus port
    volumes:
      - pocket-data:/root/.pocket/config # Persist Pocket data
    environment:
    - PERSISTENCE_PATH=/root/.pocket/config
    - NODE_ENV=testnet
    - LOG_LEVEL=debug
    - RPC_ENABLED=true
    - POCKET_CORE_PASSPHRASE=${POCKET_CORE_PASSPHRASE}

volumes:
  redis-data:
  backend_node_modules:
  frontend_node_modules:
  pocket-data:

networks:
  app-network:
    driver: bridge
